/*
 * File: app/view/CustomerDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CustomerDetail', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.customerdetail',

    requires: [
        'MyApp.view.CustomerForm',
        'MyApp.view.CustomerChart',
        'MyApp.view.CustomerMap'
    ],

    config: {
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'customerform',
                title: 'Details',
                iconCls: 'compose'
            },
            {
                xtype: 'customerchart',
                title: 'Orders',
                iconCls: 'organize'
            },
            {
                xtype: 'customermap',
                title: 'Map',
                iconCls: 'maps'
            }
        ]
    }

});