/*
 * File: app/view/CustomerForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CustomerForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.customerform',

    config: {
        items: [
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        name: 'Name'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Address',
                        name: 'Address'
                    }
                ]
            },
            {
                xtype: 'container',
                defaults: {
                    margin: 6
                },
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        action: 'Save',
                        ui: 'confirm',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        action: 'Delete',
                        ui: 'decline',
                        text: 'Delete'
                    }
                ]
            }
        ]
    }

});