/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Customer',
        'CustomerOrder'
    ],
    stores: [
        'Customers',
        'CustomerOrders'
    ],
    views: [
        'MainView',
        'CustomerList',
        'CustomerDetail',
        'CustomerForm',
        'CustomerChart',
        'CustomerMap'
    ],
    controllers: [
        'Customer'
    ],
    name: 'MyApp',

    launch: function() {
        var cssPath = "sencha-touch.css",
            cssInclude = document.createElement("link"),
            disableDefaultTheme = true;

        if (Ext.os.is("BlackBerry")) {
            cssPath = "bb10.css";
        } else if (Ext.os.is("Android")) {
            cssPath = "android.css";
        } else if (Ext.os.is("Windows") && Ext.browser.is("IE10")) {
            cssPath = "wp.css";
        } else {
            disableDefaultTheme = false;
        }

        // The app is being run on BlackBerry, Android or Windows (IE10) so disable the default iOS theme
        if (disableDefaultTheme) {
            document.styleSheets[0].disabled = true;
        }

        cssInclude.setAttribute("rel", "stylesheet");
        cssInclude.setAttribute("type", "text/css");
        cssInclude.setAttribute("href", "css/" + cssPath);

        document.getElementsByTagName("head")[0].appendChild(cssInclude);
        Ext.create('MyApp.view.MainView', {fullscreen: true});
    }

});
